### ISSUE TITLE
Interesting

### ISSUE THREAD

**Issue by lwsinclair** [EastAgile/twitterbot#1]
Who is working on this? I am starting to talk with some people about this sort of subject at the end of this week in HCMC.

-Lawrence.

**Comment by giang271291** [comment]
@lwsinclair Currently me, @anhhuy1605 and @tklarryonline

**Comment by oyster** [comment]
@lwsinclair: please let us know if you need anything else. Otherwise, I am going to close this issue soon. Thanks all.
